### ISSUE TITLE
Update platform API support to 0.5

### ISSUE THREAD

**Issue by jromero** [buildpacks/tekton-integration#21]
Resources:

- [Migration Guide](https://buildpacks.io/docs/reference/spec/migration/platform-api-0.4-0.5/)

**Comment by cmoulliard** [comment]
I think that it is time to bump the Platform version to at least 0.10 otherwise we got this error
```
buildpack API version '0.7' is incompatible with the lifecycle Step failed
```
Log of the pod running the analyze step
```
env:
  - name: CNB_PLATFORM_API
    value: '0.4'
  - name: HOME
    value: /tekton/home
name: analyze
resources: {}
volumeMounts:
  - mountPath: /workspace/source
    name: ws-sc5zr
    subPath: source
  - mountPath: /workspace/cache
    name: ws-sc5zr
    subPath: cache
  - mountPath: /layers
    name: layers-dir
args:
  - '-layers=/layers'
  - '-group=/layers/group.toml'
  - '-cache-dir=/workspace/cache'
  - '-cache-image='
  - '-uid=1000'
  - '-gid=1000'
  - kind-registry.local:5000/quarkus-hello
command:
  - /cnb/lifecycle/analyzer
image: docker.io/buildpacksio/lifecycle:0.10.2@sha256:1bf8d3fc41d2fdf0ee4abdad50038ab8902ef58c74f5bcfc432c26767d889ed0
imagePullPolicy: Always
```
