### ISSUE TITLE
Support insecure registries

### ISSUE THREAD

**Issue by jromero** [buildpacks/tekton-integration#31]
> I am using https://github.com/tektoncd/catalog/blob/master/task/buildpacks/0.3/buildpacks.yaml.
> 
> Here the `APP_IMAGE` doesn't take transport style like `http` or `https`. The `tekton` staging pod makes an `https` call to the registry whereas my registry is insecure. How do I tell `tekton` to make a `http` request ?

- via @rohitsakala at https://github.com/tektoncd/catalog/issues/757

**Comment by jromero** [comment]
Hi @rohitsakala, 

This currently isn't supported by the underlying buildpacks engine (`lifecycle`). See https://github.com/buildpacks/lifecycle/issues/524. 

Thank you for bringing up the use case. I'll try to push for support this feature.

**Comment by edmund-wagner** [comment]
I'm using IP instead of a hostname as a workaround to push into my local http registry. Maybe this helps some devs until this is fixed ;)

**Comment by david-caro** [comment]
@edmund-wagner can you elaborate? Using for example just "APP_IMAGE=192.168.49.1/minikube-user/python:snap" I get the same error:
```
$ kubectl -n image-build logs minikube-user-buildpacks-pipelinerun-fjtrj-build-from-git-gkt6c -c step-analyze
ERROR: failed to get previous image: connect to repo store '192.168.49.1/minikube-user/python:snap': Get "https://192.168.49.1/v2/": x509: certificate signed by unknown authority; Get "https://192.168.49.1:443/v2/": x509: certificate signed by unknown authority
```

And still does not accept passing the http:// proto in the APP_IMAGE param.

**Comment by david-caro** [comment]
> And still does not accept passing the http:// proto in the APP_IMAGE param.

Replying to myself :), I'm using a local harbor instance, and if you have ssl configured it will redirect to all http traffic to https, just had to not configure ssl on harbor side and now it works!

**Comment by cmoulliard** [comment]
There is a workaround which is to use as registry hostname `*.local`. In this case the go-containerregistry  lib used by lifecycle will issue a HTTP call instead of a HTTPS call :-)

**Comment by metacoma** [comment]
any updates here? 

At the moment, I'm using the following workaround to use an in-cluster insecure registry:
```yaml
...
     - name: resolve-host                                                                                                                                                                                 
        runAfter:                                                                                                                                                                                          
          - copy                                                                                                                                                                                           
        taskSpec:                                                                                                                                                                                          
          results:                                                                                                                                                                                         
            - name: host-ip                                                                                                                                                                                
              description: "Resolved IP address of zot.zot.svc.cluster.local"                                                                                                                              
          steps:                                                                                                                                                                                           
            - name: get-host-ip                                                                                                                                                                            
              image: nicolaka/netshoot:latest                                                                                                                                                              
              script: |                                                                                                                                                                                    
                #!/bin/sh                                                                                                                                                                                  
                echo "Resolving IP for zot.zot.svc.cluster.local..."                                                                                                                                       
                IP=$(getent hosts zot.zot.svc.cluster.local | awk '{ print $1 }')                                                                                                                          
                echo "Resolved IP: $IP"                                                                                                                                                                    
                echo -n "$IP" > $(results.host-ip.path)                                                                                                                                                    
                                                                                                                                                                                                           
      - name: buildpack                                                                                                                                                                                    
        runAfter:                                                                                                                                                                                          
          - resolve-host                                                                                                                                                                                   
        params:                                                                                                                                                                                            
          - name: REGISTRY_IP
            value: $(tasks.resolve-host.results.host-ip)
        taskSpec:
          steps:
            - name: pack-build
              env:
                - name: CNB_INSECURE_REGISTRIES 
                  value: zot.zot;zot.zot.svc.cluster.local
              image: buildpacksio/pack:latest
              workingDir: /workspace/build
              command: 
                - pack
                - build
                - $(params.REGISTRY_IP):5000/test3:latest
                #- --buildpack-registry
                #- zot.zot:5000
                - --builder
                - paketobuildpacks/builder-jammy-tiny
                - --workspace
                - /workspace/build
                - --docker-host=inherit
                - --publish
...

```
